print("Day Converter Program")
days = float(input("Input num of Days --> "))
print(days," Days --> Hour ",days*24," Hours ")
print(days," Days --> Hour ",(days*24)*60," Minutes ")
print(days," Days --> Hour ",((days*24)*60)*60," Seconds ")